#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Baonu_Kawaii

#include "Basic.hpp"

#include "ABP_Baonu_Kawaii_classes.hpp"
#include "ABP_Baonu_Kawaii_parameters.hpp"


namespace SDK
{

// Function ABP_Baonu_Kawaii.ABP_Baonu_Kawaii_C.ExecuteUbergraph_ABP_Baonu_Kawaii
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Baonu_Kawaii_C::ExecuteUbergraph_ABP_Baonu_Kawaii(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Baonu_Kawaii_C", "ExecuteUbergraph_ABP_Baonu_Kawaii");

	Params::ABP_Baonu_Kawaii_C_ExecuteUbergraph_ABP_Baonu_Kawaii Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_Baonu_Kawaii.ABP_Baonu_Kawaii_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_Baonu_Kawaii_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Baonu_Kawaii_C", "BlueprintUpdateAnimation");

	Params::ABP_Baonu_Kawaii_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_Baonu_Kawaii.ABP_Baonu_Kawaii_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Baonu_Kawaii_AnimGraphNode_KawaiiPhysics_EE05750F4868635E6F41C78CCDA6476E
// (BlueprintEvent)

void UABP_Baonu_Kawaii_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Baonu_Kawaii_AnimGraphNode_KawaiiPhysics_EE05750F4868635E6F41C78CCDA6476E()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Baonu_Kawaii_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Baonu_Kawaii_AnimGraphNode_KawaiiPhysics_EE05750F4868635E6F41C78CCDA6476E");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Baonu_Kawaii.ABP_Baonu_Kawaii_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Baonu_Kawaii_AnimGraphNode_KawaiiPhysics_55826383483F3FDFB6558CA350A1B2AB
// (BlueprintEvent)

void UABP_Baonu_Kawaii_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Baonu_Kawaii_AnimGraphNode_KawaiiPhysics_55826383483F3FDFB6558CA350A1B2AB()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Baonu_Kawaii_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Baonu_Kawaii_AnimGraphNode_KawaiiPhysics_55826383483F3FDFB6558CA350A1B2AB");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Baonu_Kawaii.ABP_Baonu_Kawaii_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Baonu_Kawaii_AnimGraphNode_KawaiiPhysics_7F7931364D852F84FEFC5B8036F6CB9A
// (BlueprintEvent)

void UABP_Baonu_Kawaii_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Baonu_Kawaii_AnimGraphNode_KawaiiPhysics_7F7931364D852F84FEFC5B8036F6CB9A()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Baonu_Kawaii_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Baonu_Kawaii_AnimGraphNode_KawaiiPhysics_7F7931364D852F84FEFC5B8036F6CB9A");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Baonu_Kawaii.ABP_Baonu_Kawaii_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Baonu_Kawaii_AnimGraphNode_KawaiiPhysics_98A69D2F44A194E567E8F09D253993EF
// (BlueprintEvent)

void UABP_Baonu_Kawaii_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Baonu_Kawaii_AnimGraphNode_KawaiiPhysics_98A69D2F44A194E567E8F09D253993EF()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Baonu_Kawaii_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Baonu_Kawaii_AnimGraphNode_KawaiiPhysics_98A69D2F44A194E567E8F09D253993EF");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Baonu_Kawaii.ABP_Baonu_Kawaii_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Baonu_Kawaii_AnimGraphNode_KawaiiPhysics_3B5E3D9F42902659D8592FBF064091B2
// (BlueprintEvent)

void UABP_Baonu_Kawaii_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Baonu_Kawaii_AnimGraphNode_KawaiiPhysics_3B5E3D9F42902659D8592FBF064091B2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Baonu_Kawaii_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Baonu_Kawaii_AnimGraphNode_KawaiiPhysics_3B5E3D9F42902659D8592FBF064091B2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Baonu_Kawaii.ABP_Baonu_Kawaii_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Baonu_Kawaii_AnimGraphNode_BlendListByBool_D24EE33842705D0F95F3CFAEAF56E5B7
// (BlueprintEvent)

void UABP_Baonu_Kawaii_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Baonu_Kawaii_AnimGraphNode_BlendListByBool_D24EE33842705D0F95F3CFAEAF56E5B7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Baonu_Kawaii_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Baonu_Kawaii_AnimGraphNode_BlendListByBool_D24EE33842705D0F95F3CFAEAF56E5B7");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_Baonu_Kawaii.ABP_Baonu_Kawaii_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPoseLink&                 InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_Baonu_Kawaii_C::AnimGraph(const struct FPoseLink& InPose, struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Baonu_Kawaii_C", "AnimGraph");

	Params::ABP_Baonu_Kawaii_C_AnimGraph Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function ABP_Baonu_Kawaii.ABP_Baonu_Kawaii_C.NewKawaiiLayer
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// bool                                    bEnableKawaiiSetting_0                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const class FString&                    CurrentKawaiiState                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class UPlayerAnimInstance*              OwnerInstance_0                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsPhantom                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FPoseLink*                       NewKawaiiLayer_0                                       (Parm, OutParm, NoDestructor)

void UABP_Baonu_Kawaii_C::NewKawaiiLayer(const struct FPoseLink& InPose, bool bEnableKawaiiSetting_0, const class FString& CurrentKawaiiState, class UPlayerAnimInstance* OwnerInstance_0, bool IsPhantom, struct FPoseLink* NewKawaiiLayer_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Baonu_Kawaii_C", "NewKawaiiLayer");

	Params::ABP_Baonu_Kawaii_C_NewKawaiiLayer Parms{};

	Parms.InPose = std::move(InPose);
	Parms.bEnableKawaiiSetting_0 = bEnableKawaiiSetting_0;
	Parms.CurrentKawaiiState = std::move(CurrentKawaiiState);
	Parms.OwnerInstance_0 = OwnerInstance_0;
	Parms.IsPhantom = IsPhantom;

	UObject::ProcessEvent(Func, &Parms);

	if (NewKawaiiLayer_0 != nullptr)
		*NewKawaiiLayer_0 = std::move(Parms.NewKawaiiLayer_0);
}


// Function ABP_Baonu_Kawaii.ABP_Baonu_Kawaii_C.ChestLayer
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InPose_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       ChestLayer_0                                           (Parm, OutParm, NoDestructor)

void UABP_Baonu_Kawaii_C::ChestLayer(const struct FPoseLink& InPose_0, struct FPoseLink* ChestLayer_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Baonu_Kawaii_C", "ChestLayer");

	Params::ABP_Baonu_Kawaii_C_ChestLayer Parms{};

	Parms.InPose_0 = std::move(InPose_0);

	UObject::ProcessEvent(Func, &Parms);

	if (ChestLayer_0 != nullptr)
		*ChestLayer_0 = std::move(Parms.ChestLayer_0);
}


// Function ABP_Baonu_Kawaii.ABP_Baonu_Kawaii_C.InteractiveKawaiiLayer
// (HasOutParams, BlueprintCallable)
// Parameters:
// const struct FPoseLink&                 InPose_2                                               (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// bool                                    bEnableKawaiiSetting_0                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// const class FString&                    CurrentKawaiiState                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class UPlayerAnimInstance*              OwnerInstance1                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FPoseLink*                       InteractiveKawaiiLayer_0                               (Parm, OutParm, NoDestructor)

void UABP_Baonu_Kawaii_C::InteractiveKawaiiLayer(const struct FPoseLink& InPose_2, bool bEnableKawaiiSetting_0, const class FString& CurrentKawaiiState, class UPlayerAnimInstance* OwnerInstance1, struct FPoseLink* InteractiveKawaiiLayer_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_Baonu_Kawaii_C", "InteractiveKawaiiLayer");

	Params::ABP_Baonu_Kawaii_C_InteractiveKawaiiLayer Parms{};

	Parms.InPose_2 = std::move(InPose_2);
	Parms.bEnableKawaiiSetting_0 = bEnableKawaiiSetting_0;
	Parms.CurrentKawaiiState = std::move(CurrentKawaiiState);
	Parms.OwnerInstance1 = OwnerInstance1;

	UObject::ProcessEvent(Func, &Parms);

	if (InteractiveKawaiiLayer_0 != nullptr)
		*InteractiveKawaiiLayer_0 = std::move(Parms.InteractiveKawaiiLayer_0);
}

}

