#pragma once

/*
* SDK generated by Dumper-DNA
*/

// Package: ABP_Mon_GR_Youji

#include "Basic.hpp"

#include "ABP_Mon_JT_Ranger_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_Mon_GR_Youji.ABP_Mon_GR_Youji_C
// 0x0000 (0x7DD0 - 0x7DD0)
class UABP_Mon_GR_Youji_C final : public UABP_Mon_JT_Ranger_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_Mon_GR_Youji_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_Mon_GR_Youji_C")
	}
	static class UABP_Mon_GR_Youji_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Mon_GR_Youji_C>();
	}
};
DUMPER7_ASSERTS_UABP_Mon_GR_Youji_C;

}

