#pragma once

/*
* SDK generated by Dumper-DNA
*/

// Package: ABP_Mon_Gr_Baotu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "EM_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass ABP_Mon_Gr_Baotu.ABP_Mon_Gr_Baotu_C
// 0x52E0 (0x5750 - 0x0470)
class UABP_Mon_Gr_Baotu_C final : public UMonsterAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0470(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root_2;                              // 0x0478(0x0030)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x04A8(0x0118)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0x05C0(0x0108)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x06C8(0x0020)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x06E8(0x0020)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_3;                              // 0x0708(0x0048)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_3;                   // 0x0750(0x00A0)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_43;                 // 0x07F0(0x0028)()
	struct FAnimNode_PoseSnapshot                 AnimGraphNode_PoseSnapshot;                        // 0x0818(0x0090)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_26;                      // 0x08A8(0x0030)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_45;                    // 0x08D8(0x0028)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_25;                      // 0x0900(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_7;                      // 0x0930(0x00C0)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_2;                              // 0x09F0(0x0048)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_10;                   // 0x0A38(0x0158)()
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive;                       // 0x0B90(0x00C8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_16;                   // 0x0C58(0x00E0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_15;                   // 0x0D38(0x00E0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_14;                   // 0x0E18(0x00E0)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_44;                    // 0x0EF8(0x0028)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum_1;                   // 0x0F20(0x00B0)()
	struct FAnimNode_BlendListByInt               AnimGraphNode_BlendListByInt;                      // 0x0FD0(0x00A0)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_9;                    // 0x1070(0x0158)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_43;                    // 0x11C8(0x0028)()
	struct FAnimNode_BlendListByEnum              AnimGraphNode_BlendListByEnum;                     // 0x11F0(0x00B0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_13;                   // 0x12A0(0x00E0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_12;                   // 0x1380(0x00E0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_11;                   // 0x1460(0x00E0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_10;                   // 0x1540(0x00E0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_9;                    // 0x1620(0x00E0)()
	struct FAnimNode_Root                         AnimGraphNode_Root_1;                              // 0x1700(0x0030)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_8;                    // 0x1730(0x0158)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_42;                 // 0x1888(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_41;                 // 0x18B0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_40;                 // 0x18D8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_39;                 // 0x1900(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_38;                 // 0x1928(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_37;                 // 0x1950(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_36;                 // 0x1978(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_35;                 // 0x19A0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_34;                 // 0x19C8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_33;                 // 0x19F0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_32;                 // 0x1A18(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_31;                 // 0x1A40(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_30;                 // 0x1A68(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_29;                 // 0x1A90(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_28;                 // 0x1AB8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_27;                 // 0x1AE0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_26;                 // 0x1B08(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_25;                 // 0x1B30(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_24;                 // 0x1B58(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_23;                 // 0x1B80(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_22;                 // 0x1BA8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_21;                 // 0x1BD0(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_42;                    // 0x1BF8(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_41;                    // 0x1C20(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_40;                    // 0x1C48(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_39;                    // 0x1C70(0x0028)()
	struct FAnimNode_MultiWayBlend                AnimGraphNode_MultiWayBlend_7;                     // 0x1C98(0x0050)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_24;                      // 0x1CE8(0x0030)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_38;                    // 0x1D18(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_37;                    // 0x1D40(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_36;                    // 0x1D68(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_35;                    // 0x1D90(0x0028)()
	struct FAnimNode_MultiWayBlend                AnimGraphNode_MultiWayBlend_6;                     // 0x1DB8(0x0050)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_23;                      // 0x1E08(0x0030)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_34;                    // 0x1E38(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_33;                    // 0x1E60(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_32;                    // 0x1E88(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_31;                    // 0x1EB0(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_30;                    // 0x1ED8(0x0028)()
	struct FAnimNode_MultiWayBlend                AnimGraphNode_MultiWayBlend_5;                     // 0x1F00(0x0050)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_22;                      // 0x1F50(0x0030)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_29;                    // 0x1F80(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_28;                    // 0x1FA8(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_27;                    // 0x1FD0(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_26;                    // 0x1FF8(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_25;                    // 0x2020(0x0028)()
	struct FAnimNode_MultiWayBlend                AnimGraphNode_MultiWayBlend_4;                     // 0x2048(0x0050)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_21;                      // 0x2098(0x0030)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_24;                    // 0x20C8(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_23;                    // 0x20F0(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_22;                    // 0x2118(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_21;                    // 0x2140(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_20;                    // 0x2168(0x0028)()
	struct FAnimNode_MultiWayBlend                AnimGraphNode_MultiWayBlend_3;                     // 0x2190(0x0050)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_20;                      // 0x21E0(0x0030)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_19;                    // 0x2210(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_18;                    // 0x2238(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_17;                    // 0x2260(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_16;                    // 0x2288(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_15;                    // 0x22B0(0x0028)()
	struct FAnimNode_MultiWayBlend                AnimGraphNode_MultiWayBlend_2;                     // 0x22D8(0x0050)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_19;                      // 0x2328(0x0030)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_14;                    // 0x2358(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_13;                    // 0x2380(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_12;                    // 0x23A8(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_11;                    // 0x23D0(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_10;                    // 0x23F8(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_9;                     // 0x2420(0x0028)()
	struct FAnimNode_MultiWayBlend                AnimGraphNode_MultiWayBlend_1;                     // 0x2448(0x0050)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_18;                      // 0x2498(0x0030)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_8;                     // 0x24C8(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_7;                     // 0x24F0(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_6;                     // 0x2518(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_5;                     // 0x2540(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_4;                     // 0x2568(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_3;                     // 0x2590(0x0028)()
	struct FAnimNode_MultiWayBlend                AnimGraphNode_MultiWayBlend;                       // 0x25B8(0x0050)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_17;                      // 0x2608(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_6;                      // 0x2638(0x00C0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_16;                      // 0x26F8(0x0030)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_20;                 // 0x2728(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_19;                 // 0x2750(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_18;                 // 0x2778(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_17;                 // 0x27A0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_16;                 // 0x27C8(0x0028)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_2;                   // 0x27F0(0x00A0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_8;                    // 0x2890(0x00E0)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_7;                    // 0x2970(0x00E0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_15;                      // 0x2A50(0x0030)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_9;                  // 0x2A80(0x0158)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_1;                   // 0x2BD8(0x00A0)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_8;                  // 0x2C78(0x0158)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_14;                      // 0x2DD0(0x0030)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_15;                 // 0x2E00(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_14;                 // 0x2E28(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_6;                    // 0x2E50(0x00E0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_13;                      // 0x2F30(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5;                    // 0x2F60(0x00E0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_12;                      // 0x3040(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_5;                      // 0x3070(0x00C0)()
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator;                   // 0x3130(0x00A8)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x31D8(0x00A0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_11;                      // 0x3278(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_4;                      // 0x32A8(0x00C0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_10;                      // 0x3368(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_3;                      // 0x3398(0x00C0)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_7;                    // 0x3458(0x0158)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_6;                    // 0x35B0(0x0158)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_5;                    // 0x3708(0x0158)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_4;                    // 0x3860(0x0158)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_3;                    // 0x39B8(0x0158)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_2;                    // 0x3B10(0x0158)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_1;                    // 0x3C68(0x0158)()
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x3DC0(0x0158)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_7;                  // 0x3F18(0x0158)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_6;                  // 0x4070(0x0158)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_5;                  // 0x41C8(0x0158)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_4;                  // 0x4320(0x0158)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_3;                  // 0x4478(0x0158)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_2;                  // 0x45D0(0x0158)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer_1;                  // 0x4728(0x0158)()
	struct FAnimNode_BlendSpacePlayer             AnimGraphNode_BlendSpacePlayer;                    // 0x4880(0x0158)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_13;                 // 0x49D8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_12;                 // 0x4A00(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_11;                 // 0x4A28(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_10;                 // 0x4A50(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_9;                  // 0x4A78(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_8;                  // 0x4AA0(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_7;                  // 0x4AC8(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_6;                  // 0x4AF0(0x0028)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4;                    // 0x4B18(0x00E0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_9;                       // 0x4BF8(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0x4C28(0x00E0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_8;                       // 0x4D08(0x0030)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_5;                  // 0x4D38(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_4;                  // 0x4D60(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_3;                  // 0x4D88(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_2;                  // 0x4DB0(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_2;                     // 0x4DD8(0x0028)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_7;                       // 0x4E00(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x4E30(0x00E0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_6;                       // 0x4F10(0x0030)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult_1;                  // 0x4F40(0x0028)()
	struct FAnimNode_TransitionResult             AnimGraphNode_TransitionResult;                    // 0x4F68(0x0028)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x4F90(0x0028)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_5;                       // 0x4FB8(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x4FE8(0x00E0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_4;                       // 0x50C8(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x50F8(0x00E0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_3;                       // 0x51D8(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_2;                      // 0x5208(0x00C0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_2;                       // 0x52C8(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine_1;                      // 0x52F8(0x00C0)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult_1;                       // 0x53B8(0x0030)()
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x53E8(0x0028)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x5410(0x0030)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x5440(0x00C0)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x5500(0x0030)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer_1;                   // 0x5530(0x00C0)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot_1;                              // 0x55F0(0x0048)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x5638(0x0048)()
	struct FAnimNode_LinkedAnimLayer              AnimGraphNode_LinkedAnimLayer;                     // 0x5680(0x00C0)()
	class UCurveFloat*                            PelvisShakeCurve;                                  // 0x5740(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         PelvisShake;                                       // 0x5748(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         PelvisStrength;                                    // 0x574C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_ABP_Mon_Gr_Baotu(int32 EntryPoint);
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_F129E9ED4023A6583B36D1AD49C671DE();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_0355CC3E4C182F1A602B1EB02BEFCDDD();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_A5F48B4D4D9BAA42667463B8B521434C();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_54C0207D4A78DA37A7D1F6BB25D89DBF();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_FFDFF1744C262FF3BC4A77B28B718DC8();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_B37B97EF4B0C69FA45FCDCBE35A4978F();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_D078287D43A097C0E9813F8FA698745D();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_03A99FB246D9563B86A77991C3E00819();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_5260AF004265E58804CAF1BE668FFFC4();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_D3491E3B40B7C38D458549A996A0B0C1();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_6235C9DF4F237822369E1ABA08BC2566();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_D92FFBBD4AA1B465CA1D72989F30C852();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_052D858B4B46EC5DED92ACB8C0E75C27();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_4C5A94B340392F1BD9FD04965B5ECAD3();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_D92BB19D4FA9BB389006768AF7F0B781();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_92B55415456D3E2A7F75DDABA24FA61B();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_31D6BA84483ECBDFB2365DAFAAF409C4();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_6AD4754A407583E753DA9DAED9920BEF();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_C6190B0C41F842F4EB84B8B72E0CAC23();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_9A23566949A336715213378EB304F9B6();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_B49F6B2044A3890311E0C3B96BEBF0E7();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_15A144684B54AD6B17657EA6572D968E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_30A3F0704EF9BA3E5C2C6FA4FF3BFD74();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_BA80946045F372C7540C309A18B1EDC0();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_F9125A6B40D49E45B32F0381E65E8F77();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_64AA2A594536192B0337AABDAD2981EB();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_BlendListByBool_9746EF5A4CB4CF4208D064A10E12F172();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_C72971184E339302B22EA6AA5B1B975E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_EF5656F04250C29D59630EA622BDDE05();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_933C12DF470DE030640B05A084C7C7B5();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_BlendListByBool_B5487A3549FF887310A52DB822B1AAA0();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_SequenceEvaluator_B76B5A1446A1E16035F45DBBD60E1288();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_4F5BE1D04ED693C610BA0FBE8A806CDC();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_586BA20A4DB6525945637F84973CE8E5();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_CFA5FFF14B4233719E59EB83B7F5892C();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_973E853D4128252FD8B29B9EC012055E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_D5F030F64AE205107422639181E31D42();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_C8D6907649EE3EDF744CDABA252C81C6();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_49627D544E95434180104281D9B57151();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_F87B1A72448A2F675A0673BE3CBA582B();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_TransitionResult_39D0F9674243C66DA6A93B852BF43715();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_ModifyBone_1B44300C457C3764345758B57E0AACC1();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_Mon_Gr_Baotu_AnimGraphNode_ApplyAdditive_54E5EE144DA99FFEB2676C82CABA8EB4();
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void BaseLayer(struct FPoseLink* BaseLayer_0);
	void HitAndDeadLayer(const struct FPoseLink& InPose, struct FPoseLink* HitAndDeadLayer_0);

	class FString GetModuleName() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_Mon_Gr_Baotu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_Mon_Gr_Baotu_C")
	}
	static class UABP_Mon_Gr_Baotu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Mon_Gr_Baotu_C>();
	}
};
DUMPER7_ASSERTS_UABP_Mon_Gr_Baotu_C;

}

