#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ArmoryLocation

#include "Basic.hpp"

#include "BP_ArmoryLocation_classes.hpp"
#include "BP_ArmoryLocation_parameters.hpp"


namespace SDK
{

// Function BP_ArmoryLocation.BP_ArmoryLocation_C.ExecuteUbergraph_BP_ArmoryLocation
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ArmoryLocation_C::ExecuteUbergraph_BP_ArmoryLocation(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ArmoryLocation_C", "ExecuteUbergraph_BP_ArmoryLocation");

	Params::BP_ArmoryLocation_C_ExecuteUbergraph_BP_ArmoryLocation Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ArmoryLocation.BP_ArmoryLocation_C.ReceiveEndPlay
// (Native, Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ArmoryLocation_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ArmoryLocation_C", "ReceiveEndPlay");

	Params::BP_ArmoryLocation_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_ArmoryLocation.BP_ArmoryLocation_C.ReceiveBeginPlay
// (Native, Event, Protected, BlueprintEvent)

void ABP_ArmoryLocation_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ArmoryLocation_C", "ReceiveBeginPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_ArmoryLocation.BP_ArmoryLocation_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString ABP_ArmoryLocation_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ArmoryLocation_C", "GetModuleName");

	Params::BP_ArmoryLocation_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

