#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AnimNotifyState_ForceSetExtractZVelocity

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AnimNotifyState_ForceSetExtractZVelocity.BP_AnimNotifyState_ForceSetExtractZVelocity_C
// 0x0000 (0x0030 - 0x0030)
class UBP_AnimNotifyState_ForceSetExtractZVelocity_C final : public UAnimNotifyState
{
public:
	bool Received_NotifyBegin(class USkeletalMeshComponent* meshComp, class UAnimSequenceBase* Animation, float TotalDuration) const;
	bool Received_NotifyEnd(class USkeletalMeshComponent* meshComp, class UAnimSequenceBase* Animation) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AnimNotifyState_ForceSetExtractZVelocity_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AnimNotifyState_ForceSetExtractZVelocity_C")
	}
	static class UBP_AnimNotifyState_ForceSetExtractZVelocity_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AnimNotifyState_ForceSetExtractZVelocity_C>();
	}
};
DUMPER7_ASSERTS_UBP_AnimNotifyState_ForceSetExtractZVelocity_C;

}

