#pragma once

/*
* SDK generated by Dumper-DNA
*/

// Package: BP_BuffManager

#include "Basic.hpp"

#include "BP_BuffManager_classes.hpp"
#include "BP_BuffManager_parameters.hpp"


namespace SDK
{

// Function BP_BuffManager.BP_BuffManager_C.ExecuteUbergraph_BP_BuffManager
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BuffManager_C::ExecuteUbergraph_BP_BuffManager(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuffManager_C", "ExecuteUbergraph_BP_BuffManager");

	Params::BP_BuffManager_C_ExecuteUbergraph_BP_BuffManager Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BuffManager.BP_BuffManager_C.ReceiveBeginPlay
// (Native, Event, Public, BlueprintEvent)

void UBP_BuffManager_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuffManager_C", "ReceiveBeginPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_BuffManager.BP_BuffManager_C.SetFXMIDMatrerialsParams
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMeshComponent*                   MeshComponent                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ParamValue                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BuffManager_C::SetFXMIDMatrerialsParams(class UMeshComponent* MeshComponent, float ParamValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuffManager_C", "SetFXMIDMatrerialsParams");

	Params::BP_BuffManager_C_SetFXMIDMatrerialsParams Parms{};

	Parms.MeshComponent = MeshComponent;
	Parms.ParamValue = ParamValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BuffManager.BP_BuffManager_C.ClearFXMIDMatrerialsParams
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMeshComponent*                   MeshComponent                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BuffManager_C::ClearFXMIDMatrerialsParams(class UMeshComponent* MeshComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuffManager_C", "ClearFXMIDMatrerialsParams");

	Params::BP_BuffManager_C_ClearFXMIDMatrerialsParams Parms{};

	Parms.MeshComponent = MeshComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BuffManager.BP_BuffManager_C.SetFrenelParams
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMeshComponent*                   MeshComponent                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   FresnelColorRange                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FLinearColor&              FresnelColor                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   FresnelColorStrength                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BuffManager_C::SetFrenelParams(class UMeshComponent* MeshComponent, float FresnelColorRange, const struct FLinearColor& FresnelColor, float FresnelColorStrength)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuffManager_C", "SetFrenelParams");

	Params::BP_BuffManager_C_SetFrenelParams Parms{};

	Parms.MeshComponent = MeshComponent;
	Parms.FresnelColorRange = FresnelColorRange;
	Parms.FresnelColor = std::move(FresnelColor);
	Parms.FresnelColorStrength = FresnelColorStrength;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BuffManager.BP_BuffManager_C.CopyMonsterParams
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMaterialInterface*               ParentMat                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UMaterialInstanceDynamic*         NewMat                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BuffManager_C::CopyMonsterParams(class UMaterialInterface* ParentMat, class UMaterialInstanceDynamic* NewMat)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuffManager_C", "CopyMonsterParams");

	Params::BP_BuffManager_C_CopyMonsterParams Parms{};

	Parms.ParentMat = ParentMat;
	Parms.NewMat = NewMat;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BuffManager.BP_BuffManager_C.AddBuff
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMaterialInstanceDynamic*         Material                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ElementIndex                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              TargetMesh                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BuffManager_C::AddBuff(class UMaterialInstanceDynamic* Material, int32 ElementIndex, class UPrimitiveComponent* TargetMesh)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuffManager_C", "AddBuff");

	Params::BP_BuffManager_C_AddBuff Parms{};

	Parms.Material = Material;
	Parms.ElementIndex = ElementIndex;
	Parms.TargetMesh = TargetMesh;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BuffManager.BP_BuffManager_C.ClearBuff
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UMaterialInstanceDynamic*         Material                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   ElementIndex                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_BuffManager_C::ClearBuff(class UMaterialInstanceDynamic* Material, int32 ElementIndex, class UPrimitiveComponent* Target)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuffManager_C", "ClearBuff");

	Params::BP_BuffManager_C_ClearBuff Parms{};

	Parms.Material = Material;
	Parms.ElementIndex = ElementIndex;
	Parms.Target = Target;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BuffManager.BP_BuffManager_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString UBP_BuffManager_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuffManager_C", "GetModuleName");

	Params::BP_BuffManager_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

