#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ChestInteractiveComponent

#include "Basic.hpp"

#include "BP_ChestInteractiveComponent_classes.hpp"
#include "BP_ChestInteractiveComponent_parameters.hpp"


namespace SDK
{

// Function BP_ChestInteractiveComponent.BP_ChestInteractiveComponent_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString UBP_ChestInteractiveComponent_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ChestInteractiveComponent_C", "GetModuleName");

	Params::BP_ChestInteractiveComponent_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

