#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CombatPropBase

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "EM_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CombatPropBase.BP_CombatPropBase_C
// 0x0038 (0x0CB0 - 0x0C78)
class ABP_CombatPropBase_C : public ACombatPropBase
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0C78(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             NewVar_0;                                          // 0x0C80(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void Play_Fx_at_Location(class USceneComponent* 目标, const class FString& NiagaraPath, const class FString& InputName, bool Cache, const struct FVector& LocationOffset, const struct FRotator& RotationOffset, const struct FVector& Scale, class FString* OutputName);

	class FString GetModuleName() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CombatPropBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CombatPropBase_C")
	}
	static class ABP_CombatPropBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CombatPropBase_C>();
	}
};
DUMPER7_ASSERTS_ABP_CombatPropBase_C;

}

