#pragma once

/*
* SDK generated by Dumper-DNA
*/

// Package: BP_Common_Addbuff

#include "Basic.hpp"

#include "BP_Common_Addbuff_classes.hpp"
#include "BP_Common_Addbuff_parameters.hpp"


namespace SDK
{

// Function BP_Common_Addbuff.BP_Common_Addbuff_C.ExecuteUbergraph_BP_Common_Addbuff
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Common_Addbuff_C::ExecuteUbergraph_BP_Common_Addbuff(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Common_Addbuff_C", "ExecuteUbergraph_BP_Common_Addbuff");

	Params::BP_Common_Addbuff_C_ExecuteUbergraph_BP_Common_Addbuff Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Common_Addbuff.BP_Common_Addbuff_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UBP_Common_Addbuff_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Common_Addbuff_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

