#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ExploreBadgeShopCamera

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_ExploreBadgeShopCamera.BP_ExploreBadgeShopCamera_C.ExecuteUbergraph_BP_ExploreBadgeShopCamera
// 0x0004 (0x0004 - 0x0000)
struct BP_ExploreBadgeShopCamera_C_ExecuteUbergraph_BP_ExploreBadgeShopCamera final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_ExploreBadgeShopCamera_C_ExecuteUbergraph_BP_ExploreBadgeShopCamera;

}

