#pragma once

/*
* SDK generated by Dumper-DNA
*/

// Package: BP_EMGameMode_Balcony_01

#include "Basic.hpp"

#include "BP_EMGameMode_Balcony_01_classes.hpp"
#include "BP_EMGameMode_Balcony_01_parameters.hpp"


namespace SDK
{

// Function BP_EMGameMode_Balcony_01.BP_EMGameMode_Balcony_01_C.ExecuteUbergraph_BP_EMGameMode_Balcony_01
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EMGameMode_Balcony_01_C::ExecuteUbergraph_BP_EMGameMode_Balcony_01(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EMGameMode_Balcony_01_C", "ExecuteUbergraph_BP_EMGameMode_Balcony_01");

	Params::BP_EMGameMode_Balcony_01_C_ExecuteUbergraph_BP_EMGameMode_Balcony_01 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EMGameMode_Balcony_01.BP_EMGameMode_Balcony_01_C.BndEvt__BP_EMGameMode_Balcony_01_AfterPetQuestFinish_K2Node_ComponentBoundEvent_1_AfterQuestFinishEvent__DelegateSignature
// (BlueprintEvent)

void ABP_EMGameMode_Balcony_01_C::BndEvt__BP_EMGameMode_Balcony_01_AfterPetQuestFinish_K2Node_ComponentBoundEvent_1_AfterQuestFinishEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EMGameMode_Balcony_01_C", "BndEvt__BP_EMGameMode_Balcony_01_AfterPetQuestFinish_K2Node_ComponentBoundEvent_1_AfterQuestFinishEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EMGameMode_Balcony_01.BP_EMGameMode_Balcony_01_C.BndEvt__BP_EMGameMode_Balcony_01_AfterQuestFinishEvent_K2Node_ComponentBoundEvent_0_AfterQuestFinishEvent__DelegateSignature
// (BlueprintEvent)

void ABP_EMGameMode_Balcony_01_C::BndEvt__BP_EMGameMode_Balcony_01_AfterQuestFinishEvent_K2Node_ComponentBoundEvent_0_AfterQuestFinishEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EMGameMode_Balcony_01_C", "BndEvt__BP_EMGameMode_Balcony_01_AfterQuestFinishEvent_K2Node_ComponentBoundEvent_0_AfterQuestFinishEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EMGameMode_Balcony_01.BP_EMGameMode_Balcony_01_C.Prologue_Balcony_FinishSearch
// (BlueprintCallable, BlueprintEvent)

void ABP_EMGameMode_Balcony_01_C::Prologue_Balcony_FinishSearch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EMGameMode_Balcony_01_C", "Prologue_Balcony_FinishSearch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EMGameMode_Balcony_01.BP_EMGameMode_Balcony_01_C.Prologue_Balcony_EnterBuilding
// (BlueprintCallable, BlueprintEvent)

void ABP_EMGameMode_Balcony_01_C::Prologue_Balcony_EnterBuilding()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EMGameMode_Balcony_01_C", "Prologue_Balcony_EnterBuilding");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EMGameMode_Balcony_01.BP_EMGameMode_Balcony_01_C.OnCustomEvent
// (Native, Event, Public, BlueprintEvent)
// Parameters:
// const class FString&                    EventName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// EGameModeEventChannel                   Channel                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EMGameMode_Balcony_01_C::OnCustomEvent(const class FString& EventName, EGameModeEventChannel Channel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EMGameMode_Balcony_01_C", "OnCustomEvent");

	Params::BP_EMGameMode_Balcony_01_C_OnCustomEvent Parms{};

	Parms.EventName = std::move(EventName);
	Parms.Channel = Channel;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_EMGameMode_Balcony_01.BP_EMGameMode_Balcony_01_C.OnBigWorldActive
// (Native, Event, Public, BlueprintEvent)

void ABP_EMGameMode_Balcony_01_C::OnBigWorldActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EMGameMode_Balcony_01_C", "OnBigWorldActive");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_EMGameMode_Balcony_01.BP_EMGameMode_Balcony_01_C.LaotouhuanStart
// (BlueprintCallable, BlueprintEvent)

void ABP_EMGameMode_Balcony_01_C::LaotouhuanStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EMGameMode_Balcony_01_C", "LaotouhuanStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EMGameMode_Balcony_01.BP_EMGameMode_Balcony_01_C.LaotouhuanStop
// (BlueprintCallable, BlueprintEvent)

void ABP_EMGameMode_Balcony_01_C::LaotouhuanStop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EMGameMode_Balcony_01_C", "LaotouhuanStop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EMGameMode_Balcony_01.BP_EMGameMode_Balcony_01_C.BpOnTimerEnd
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    TimerHandleName                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void ABP_EMGameMode_Balcony_01_C::BpOnTimerEnd(const class FString& TimerHandleName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EMGameMode_Balcony_01_C", "BpOnTimerEnd");

	Params::BP_EMGameMode_Balcony_01_C_BpOnTimerEnd Parms{};

	Parms.TimerHandleName = std::move(TimerHandleName);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

