#pragma once

/*
* SDK generated by Dumper-DNA
*/

// Package: BP_EMGameState

#include "Basic.hpp"

#include "BP_EMGameState_classes.hpp"
#include "BP_EMGameState_parameters.hpp"


namespace SDK
{

// Function BP_EMGameState.BP_EMGameState_C.OnRep_ExitInfo
// (Native, BlueprintCallable, BlueprintEvent)

void ABP_EMGameState_C::OnRep_ExitInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EMGameState_C", "OnRep_ExitInfo");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_EMGameState.BP_EMGameState_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString ABP_EMGameState_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EMGameState_C", "GetModuleName");

	Params::BP_EMGameState_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

