#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InteractiveBaseComponent

#include "Basic.hpp"

#include "BP_InteractiveBaseComponent_classes.hpp"
#include "BP_InteractiveBaseComponent_parameters.hpp"


namespace SDK
{

// Function BP_InteractiveBaseComponent.BP_InteractiveBaseComponent_C.IsCanInteractive
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           PlayerActor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UBP_InteractiveBaseComponent_C::IsCanInteractive(class AActor* PlayerActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractiveBaseComponent_C", "IsCanInteractive");

	Params::BP_InteractiveBaseComponent_C_IsCanInteractive Parms{};

	Parms.PlayerActor = PlayerActor;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_InteractiveBaseComponent.BP_InteractiveBaseComponent_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString UBP_InteractiveBaseComponent_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_InteractiveBaseComponent_C", "GetModuleName");

	Params::BP_InteractiveBaseComponent_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

