#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LimitExploreStart

#include "Basic.hpp"

#include "BP_LimitExploreStart_classes.hpp"
#include "BP_LimitExploreStart_parameters.hpp"


namespace SDK
{

// Function BP_LimitExploreStart.BP_LimitExploreStart_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString ABP_LimitExploreStart_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_LimitExploreStart_C", "GetModuleName");

	Params::BP_LimitExploreStart_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

