#pragma once

/*
* SDK generated by Dumper-DNA
*/

// Package: BP_Mon_Jt_Pizhuo

#include "Basic.hpp"

#include "BP_Mon_Jt_Pizhuo_classes.hpp"
#include "BP_Mon_Jt_Pizhuo_parameters.hpp"


namespace SDK
{

// Function BP_Mon_Jt_Pizhuo.BP_Mon_Jt_Pizhuo_C.ExecuteUbergraph_BP_Mon_Jt_Pizhuo
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Mon_Jt_Pizhuo_C::ExecuteUbergraph_BP_Mon_Jt_Pizhuo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Mon_Jt_Pizhuo_C", "ExecuteUbergraph_BP_Mon_Jt_Pizhuo");

	Params::BP_Mon_Jt_Pizhuo_C_ExecuteUbergraph_BP_Mon_Jt_Pizhuo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Mon_Jt_Pizhuo.BP_Mon_Jt_Pizhuo_C.OnHitFlyLanded
// (Event, Public, BlueprintEvent)

void ABP_Mon_Jt_Pizhuo_C::OnHitFlyLanded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Mon_Jt_Pizhuo_C", "OnHitFlyLanded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Mon_Jt_Pizhuo.BP_Mon_Jt_Pizhuo_C.OnHitFlyBegan
// (Event, Public, BlueprintEvent)

void ABP_Mon_Jt_Pizhuo_C::OnHitFlyBegan()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Mon_Jt_Pizhuo_C", "OnHitFlyBegan");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Mon_Jt_Pizhuo.BP_Mon_Jt_Pizhuo_C.GetHitBones
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<class FName>*                    HitBones                                               (Parm, OutParm)

void ABP_Mon_Jt_Pizhuo_C::GetHitBones(TArray<class FName>* HitBones)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Mon_Jt_Pizhuo_C", "GetHitBones");

	Params::BP_Mon_Jt_Pizhuo_C_GetHitBones Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (HitBones != nullptr)
		*HitBones = std::move(Parms.HitBones);
}


// Function BP_Mon_Jt_Pizhuo.BP_Mon_Jt_Pizhuo_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString ABP_Mon_Jt_Pizhuo_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Mon_Jt_Pizhuo_C", "GetModuleName");

	Params::BP_Mon_Jt_Pizhuo_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

