#pragma once

/*
* SDK generated by Dumper-DNA
*/

// Package: BP_NPC

#include "Basic.hpp"

#include "BP_NPC_classes.hpp"
#include "BP_NPC_parameters.hpp"


namespace SDK
{

// Function BP_NPC.BP_NPC_C.ExecuteUbergraph_BP_NPC
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_NPC_C::ExecuteUbergraph_BP_NPC(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPC_C", "ExecuteUbergraph_BP_NPC");

	Params::BP_NPC_C_ExecuteUbergraph_BP_NPC Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_NPC.BP_NPC_C.Event_NPC_Mouth
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// Enum_NPC_Exp_Mouth                      MouthEnum                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Rate                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_NPC_C::Event_NPC_Mouth(Enum_NPC_Exp_Mouth MouthEnum, float Rate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPC_C", "Event_NPC_Mouth");

	Params::BP_NPC_C_Event_NPC_Mouth Parms{};

	Parms.MouthEnum = MouthEnum;
	Parms.Rate = Rate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_NPC.BP_NPC_C.Event_NPC_Blink
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// Enum_NPC_Exp_Eyes                       EyeEnum                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Rate                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_NPC_C::Event_NPC_Blink(Enum_NPC_Exp_Eyes EyeEnum, float Rate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPC_C", "Event_NPC_Blink");

	Params::BP_NPC_C_Event_NPC_Blink Parms{};

	Parms.EyeEnum = EyeEnum;
	Parms.Rate = Rate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_NPC.BP_NPC_C.ReceiveBeginPlay
// (Native, Event, Protected, BlueprintEvent)

void ABP_NPC_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPC_C", "ReceiveBeginPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_NPC.BP_NPC_C.MouthTimeline__UpdateFunc
// (BlueprintEvent)

void ABP_NPC_C::MouthTimeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPC_C", "MouthTimeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_NPC.BP_NPC_C.MouthTimeline__FinishedFunc
// (BlueprintEvent)

void ABP_NPC_C::MouthTimeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPC_C", "MouthTimeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_NPC.BP_NPC_C.EyeTimeline__UpdateFunc
// (BlueprintEvent)

void ABP_NPC_C::EyeTimeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPC_C", "EyeTimeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_NPC.BP_NPC_C.EyeTimeline__FinishedFunc
// (BlueprintEvent)

void ABP_NPC_C::EyeTimeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPC_C", "EyeTimeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_NPC.BP_NPC_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_NPC_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPC_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_NPC.BP_NPC_C.PlayDefaultFacialInEditor
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_NPC_C::PlayDefaultFacialInEditor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPC_C", "PlayDefaultFacialInEditor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_NPC.BP_NPC_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString ABP_NPC_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_NPC_C", "GetModuleName");

	Params::BP_NPC_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

