#pragma once

/*
* SDK generated by Dumper-DNA
*/

// Package: BP_NewTargetArea

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_NewTargetArea.BP_NewTargetArea_C.ExecuteUbergraph_BP_NewTargetArea
// 0x0004 (0x0004 - 0x0000)
struct BP_NewTargetArea_C_ExecuteUbergraph_BP_NewTargetArea final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_NewTargetArea_C_ExecuteUbergraph_BP_NewTargetArea;

// Function BP_NewTargetArea.BP_NewTargetArea_C.GetModuleName
// 0x0010 (0x0010 - 0x0000)
struct BP_NewTargetArea_C_GetModuleName final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_NewTargetArea_C_GetModuleName;

}

