#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NPC_JT_Pizhuo_Laugh

#include "Basic.hpp"

#include "BP_NPC_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_NPC_JT_Pizhuo_Laugh.BP_NPC_JT_Pizhuo_Laugh_C
// 0x0010 (0x2270 - 0x2260)
class ABP_NPC_JT_Pizhuo_Laugh_C final : public ABP_NPC_C
{
public:
	class URectLightComponent*                    RectLight;                                         // 0x2260(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_NPC_JT_Pizhuo_Laugh_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_NPC_JT_Pizhuo_Laugh_C")
	}
	static class ABP_NPC_JT_Pizhuo_Laugh_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NPC_JT_Pizhuo_Laugh_C>();
	}
};
DUMPER7_ASSERTS_ABP_NPC_JT_Pizhuo_Laugh_C;

}

