#pragma once

/*
* SDK generated by Dumper-DNA
*/

// Package: BP_SeatBase

#include "Basic.hpp"

#include "BP_SeatBase_classes.hpp"
#include "BP_SeatBase_parameters.hpp"


namespace SDK
{

// Function BP_SeatBase.BP_SeatBase_C.ExecuteUbergraph_BP_SeatBase
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SeatBase_C::ExecuteUbergraph_BP_SeatBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SeatBase_C", "ExecuteUbergraph_BP_SeatBase");

	Params::BP_SeatBase_C_ExecuteUbergraph_BP_SeatBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SeatBase.BP_SeatBase_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString ABP_SeatBase_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SeatBase_C", "GetModuleName");

	Params::BP_SeatBase_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

