#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SeatPointComponent

#include "Basic.hpp"

#include "BP_SeatPointComponent_classes.hpp"
#include "BP_SeatPointComponent_parameters.hpp"


namespace SDK
{

// Function BP_SeatPointComponent.BP_SeatPointComponent_C.ExecuteUbergraph_BP_SeatPointComponent
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_SeatPointComponent_C::ExecuteUbergraph_BP_SeatPointComponent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SeatPointComponent_C", "ExecuteUbergraph_BP_SeatPointComponent");

	Params::BP_SeatPointComponent_C_ExecuteUbergraph_BP_SeatPointComponent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SeatPointComponent.BP_SeatPointComponent_C.ReceiveBeginPlay
// (Native, Event, Public, BlueprintEvent)

void UBP_SeatPointComponent_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SeatPointComponent_C", "ReceiveBeginPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function BP_SeatPointComponent.BP_SeatPointComponent_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString UBP_SeatPointComponent_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SeatPointComponent_C", "GetModuleName");

	Params::BP_SeatPointComponent_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

