#pragma once

/*
* SDK generated by Dumper-DNA
*/

// Package: BP_WeaponFashion

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_WeaponFashion.BP_WeaponFashion_C.GetMaterial
// 0x0008 (0x0008 - 0x0000)
struct BP_WeaponFashion_C_GetMaterial final
{
public:
	class UMaterialInstanceDynamic*               NewParam;                                          // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_WeaponFashion_C_GetMaterial;

// Function BP_WeaponFashion.BP_WeaponFashion_C.GetModuleName
// 0x0010 (0x0010 - 0x0000)
struct BP_WeaponFashion_C_GetModuleName final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_WeaponFashion_C_GetModuleName;

}

