#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CharPointLight

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CharPointLight.CharPointLight_C
// 0x0008 (0x02C0 - 0x02B8)
class ACharPointLight_C final : public APointLight
{
public:
	class UMaterialBillboardComponent*            MaterialBillboard;                                 // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CharPointLight_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CharPointLight_C")
	}
	static class ACharPointLight_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACharPointLight_C>();
	}
};
DUMPER7_ASSERTS_ACharPointLight_C;

}

