#pragma once

/*
* SDK generated by Dumper-DNA
*/

// Package: ClanManagerBase

#include "Basic.hpp"


namespace SDK::Params
{

// Function ClanManagerBase.ClanManagerBase_C.ExecuteUbergraph_ClanManagerBase
// 0x0004 (0x0004 - 0x0000)
struct ClanManagerBase_C_ExecuteUbergraph_ClanManagerBase final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_ClanManagerBase_C_ExecuteUbergraph_ClanManagerBase;

// Function ClanManagerBase.ClanManagerBase_C.GetModuleName
// 0x0010 (0x0010 - 0x0000)
struct ClanManagerBase_C_GetModuleName final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_ClanManagerBase_C_GetModuleName;

}

