#pragma once

/*
* SDK generated by Dumper-DNA
*/

// Package: ConditionComponent

#include "Basic.hpp"

#include "ConditionComponent_classes.hpp"
#include "ConditionComponent_parameters.hpp"


namespace SDK
{

// Function ConditionComponent.ConditionComponent_C.Check_Creater_Key_Int
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Creater_Key_Int(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Creater_Key_Int");

	Params::ConditionComponent_C_Check_Creater_Key_Int Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.CheckCreaterBuff
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::CheckCreaterBuff(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "CheckCreaterBuff");

	Params::ConditionComponent_C_CheckCreaterBuff Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.IsRealSummon
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::IsRealSummon(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "IsRealSummon");

	Params::ConditionComponent_C_IsRealSummon Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_SkillCreature
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_SkillCreature(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_SkillCreature");

	Params::ConditionComponent_C_Check_SkillCreature Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.BossAida_InP3orP4orP5
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::BossAida_InP3orP4orP5(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "BossAida_InP3orP4orP5");

	Params::ConditionComponent_C_BossAida_InP3orP4orP5 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.BossAida_InP1orP2
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::BossAida_InP1orP2(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "BossAida_InP1orP2");

	Params::ConditionComponent_C_BossAida_InP1orP2 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Char_AO
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Char_AO(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Char_AO");

	Params::ConditionComponent_C_Check_Char_AO Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Can_BattleProp
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   是否成功                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Can_BattleProp(bool* 是否成功)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Can_BattleProp");

	Params::ConditionComponent_C_Can_BattleProp Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (是否成功 != nullptr)
		*是否成功 = Parms.是否成功;
}


// Function ConditionComponent.ConditionComponent_C.IsQuestRole
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::IsQuestRole(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "IsQuestRole");

	Params::ConditionComponent_C_IsQuestRole Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Is_Shooting
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Is_Shooting(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Is_Shooting");

	Params::ConditionComponent_C_Is_Shooting Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.CheckInSquadDungeon
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::CheckInSquadDungeon(bool* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "CheckInSquadDungeon");

	Params::ConditionComponent_C_CheckInSquadDungeon Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}


// Function ConditionComponent.ConditionComponent_C.BossTuosi_CanUseSkill04
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::BossTuosi_CanUseSkill04(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "BossTuosi_CanUseSkill04");

	Params::ConditionComponent_C_BossTuosi_CanUseSkill04 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Mon_EX02_EscapingFromBattle
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Mon_EX02_EscapingFromBattle(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Mon_EX02_EscapingFromBattle");

	Params::ConditionComponent_C_Check_Mon_EX02_EscapingFromBattle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Is_Phantom_Dispatching
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Is_Phantom_Dispatching(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Is_Phantom_Dispatching");

	Params::ConditionComponent_C_Is_Phantom_Dispatching Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Is_OnGround
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Is_OnGround(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Is_OnGround");

	Params::ConditionComponent_C_Is_OnGround Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Can_Interactive_Paotai
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Can_Interactive_Paotai(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Can_Interactive_Paotai");

	Params::ConditionComponent_C_Can_Interactive_Paotai Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_ComboLevel
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_ComboLevel(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_ComboLevel");

	Params::ConditionComponent_C_Check_ComboLevel Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Not_PerfectHeavyShooting
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Not_PerfectHeavyShooting(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Not_PerfectHeavyShooting");

	Params::ConditionComponent_C_Not_PerfectHeavyShooting Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.CustomizedTargets_IsValid
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::CustomizedTargets_IsValid(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "CustomizedTargets_IsValid");

	Params::ConditionComponent_C_CustomizedTargets_IsValid Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Is_HighEnough
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Is_HighEnough(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Is_HighEnough");

	Params::ConditionComponent_C_Is_HighEnough Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Mon_UnitId
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Mon_UnitId(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Mon_UnitId");

	Params::ConditionComponent_C_Check_Mon_UnitId Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Magazine_Zero
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Magazine_Zero(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Magazine_Zero");

	Params::ConditionComponent_C_Magazine_Zero Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_HeavyCharge_Grade
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_HeavyCharge_Grade(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_HeavyCharge_Grade");

	Params::ConditionComponent_C_Check_HeavyCharge_Grade Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Buff_Type
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Buff_Type(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Buff_Type");

	Params::ConditionComponent_C_Check_Buff_Type Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.SummonNumMore_Arbitray
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::SummonNumMore_Arbitray(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "SummonNumMore_Arbitray");

	Params::ConditionComponent_C_SummonNumMore_Arbitray Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Heitao_SkillGrade6
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Heitao_SkillGrade6(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Heitao_SkillGrade6");

	Params::ConditionComponent_C_Check_Heitao_SkillGrade6 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Is_In_Rouge
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UConditionComponent_C::Is_In_Rouge()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Is_In_Rouge");

	Params::ConditionComponent_C_Is_In_Rouge Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function ConditionComponent.ConditionComponent_C.CheckNotifyCondition
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   EffectId_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   CombatConditionId                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ACharacterBase*                   Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UConditionComponent_C::CheckNotifyCondition(int32 EffectId_0, int32 CombatConditionId, class ACharacterBase* Source)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "CheckNotifyCondition");

	Params::ConditionComponent_C_CheckNotifyCondition Parms{};

	Parms.EffectId_0 = EffectId_0;
	Parms.CombatConditionId = CombatConditionId;
	Parms.Source = Source;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function ConditionComponent.ConditionComponent_C.Check_BTTarget_Buff
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_BTTarget_Buff(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_BTTarget_Buff");

	Params::ConditionComponent_C_Check_BTTarget_Buff Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Mon_IsInBattle
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Mon_IsInBattle(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Mon_IsInBattle");

	Params::ConditionComponent_C_Check_Mon_IsInBattle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Mon_IsActive
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Mon_IsActive(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Mon_IsActive");

	Params::ConditionComponent_C_Check_Mon_IsActive Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Mon_CorpType
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Mon_CorpType(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Mon_CorpType");

	Params::ConditionComponent_C_Check_Mon_CorpType Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Mon_BBValue_ObjectIsNull
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Mon_BBValue_ObjectIsNull(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Mon_BBValue_ObjectIsNull");

	Params::ConditionComponent_C_Check_Mon_BBValue_ObjectIsNull Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Mon_BBValue_Int
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Mon_BBValue_Int(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Mon_BBValue_Int");

	Params::ConditionComponent_C_Check_Mon_BBValue_Int Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Mon_BBValue
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Mon_BBValue(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Mon_BBValue");

	Params::ConditionComponent_C_Check_Mon_BBValue Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Is_In_Stun
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UConditionComponent_C::Is_In_Stun()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Is_In_Stun");

	Params::ConditionComponent_C_Is_In_Stun Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function ConditionComponent.ConditionComponent_C.Check_Maer_PassiveBuff
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Maer_PassiveBuff(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Maer_PassiveBuff");

	Params::ConditionComponent_C_Check_Maer_PassiveBuff Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Mon_HpPercentUnder
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Mon_HpPercentUnder(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Mon_HpPercentUnder");

	Params::ConditionComponent_C_Check_Mon_HpPercentUnder Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Mon_Dungeon_EscapingFromBattle
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Mon_Dungeon_EscapingFromBattle(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Mon_Dungeon_EscapingFromBattle");

	Params::ConditionComponent_C_Check_Mon_Dungeon_EscapingFromBattle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Yeer_Skill01B
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Yeer_Skill01B(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Yeer_Skill01B");

	Params::ConditionComponent_C_Check_Yeer_Skill01B Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Yeer_Skill01A
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Yeer_Skill01A(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Yeer_Skill01A");

	Params::ConditionComponent_C_Check_Yeer_Skill01A Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Songlu_CanDash
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Songlu_CanDash(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Songlu_CanDash");

	Params::ConditionComponent_C_Check_Songlu_CanDash Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Xier_InSkill2
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Xier_InSkill2(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Xier_InSkill2");

	Params::ConditionComponent_C_Check_Xier_InSkill2 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Key_Int
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Key_Int(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Key_Int");

	Params::ConditionComponent_C_Check_Key_Int Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Key_Float
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Key_Float(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Key_Float");

	Params::ConditionComponent_C_Check_Key_Float Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Key_Bool
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Key_Bool(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Key_Bool");

	Params::ConditionComponent_C_Check_Key_Bool Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Is_In_LieDown
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// EHitFlyState                            ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

EHitFlyState UConditionComponent_C::Is_In_LieDown(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Is_In_LieDown");

	Params::ConditionComponent_C_Is_In_LieDown Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;

	return Parms.ReturnValue;
}


// Function ConditionComponent.ConditionComponent_C.Is_Seating
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Is_Seating(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Is_Seating");

	Params::ConditionComponent_C_Is_Seating Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.CheckCondition
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   CombatConditionId                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ACharacterBase*                   Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const TArray<int32>&                    TargetEids                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UConditionComponent_C::CheckCondition(int32 CombatConditionId, class ACharacterBase* Character, const TArray<int32>& TargetEids)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "CheckCondition");

	Params::ConditionComponent_C_CheckCondition Parms{};

	Parms.CombatConditionId = CombatConditionId;
	Parms.Character = Character;
	Parms.TargetEids = std::move(TargetEids);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function ConditionComponent.ConditionComponent_C.Check_Mon_Region_EscapingFromBattle
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Mon_Region_EscapingFromBattle(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Mon_Region_EscapingFromBattle");

	Params::ConditionComponent_C_Check_Mon_Region_EscapingFromBattle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Is_Idle
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Is_Idle(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Is_Idle");

	Params::ConditionComponent_C_Is_Idle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.IsStoryBoss
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   是否成功                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::IsStoryBoss(bool* 是否成功)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "IsStoryBoss");

	Params::ConditionComponent_C_IsStoryBoss Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (是否成功 != nullptr)
		*是否成功 = Parms.是否成功;
}


// Function ConditionComponent.ConditionComponent_C.Is_UnitId_Match
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Is_UnitId_Match(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Is_UnitId_Match");

	Params::ConditionComponent_C_Is_UnitId_Match Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Is_MonsterCharacter
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Is_MonsterCharacter(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Is_MonsterCharacter");

	Params::ConditionComponent_C_Is_MonsterCharacter Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Is_PlayerCharacter
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Is_PlayerCharacter(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Is_PlayerCharacter");

	Params::ConditionComponent_C_Is_PlayerCharacter Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.IsAnySceneAroundBTTarget
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::IsAnySceneAroundBTTarget(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "IsAnySceneAroundBTTarget");

	Params::ConditionComponent_C_IsAnySceneAroundBTTarget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Not_SpMax
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Not_SpMax(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Not_SpMax");

	Params::ConditionComponent_C_Not_SpMax Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Sp_Zero
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Sp_Zero(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Sp_Zero");

	Params::ConditionComponent_C_Sp_Zero Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Not_HpMax
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Not_HpMax(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Not_HpMax");

	Params::ConditionComponent_C_Not_HpMax Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Not_BulletMax
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Not_BulletMax(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Not_BulletMax");

	Params::ConditionComponent_C_Not_BulletMax Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Bullet_Zero
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Bullet_Zero(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Bullet_Zero");

	Params::ConditionComponent_C_Bullet_Zero Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.BrokenPart
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   是否成功                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::BrokenPart(bool* 是否成功)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "BrokenPart");

	Params::ConditionComponent_C_BrokenPart Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (是否成功 != nullptr)
		*是否成功 = Parms.是否成功;
}


// Function ConditionComponent.ConditionComponent_C.IsRecovering
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::IsRecovering(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "IsRecovering");

	Params::ConditionComponent_C_IsRecovering Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Summoner Skill 1 Hold
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Summoner_Skill_1_Hold(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Summoner Skill 1 Hold");

	Params::ConditionComponent_C_Summoner_Skill_1_Hold Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.PartIsBroken
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   是否成功                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::PartIsBroken(bool* 是否成功)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "PartIsBroken");

	Params::ConditionComponent_C_PartIsBroken Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (是否成功 != nullptr)
		*是否成功 = Parms.是否成功;
}


// Function ConditionComponent.ConditionComponent_C.Is_FallAttack_Landed
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Is_FallAttack_Landed(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Is_FallAttack_Landed");

	Params::ConditionComponent_C_Is_FallAttack_Landed Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Skill2_Hold
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Skill2_Hold(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Skill2_Hold");

	Params::ConditionComponent_C_Skill2_Hold Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Skill1_Hold
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Skill1_Hold(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Skill1_Hold");

	Params::ConditionComponent_C_Skill1_Hold Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Press_AnyAttack
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Press_AnyAttack(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Press_AnyAttack");

	Params::ConditionComponent_C_Press_AnyAttack Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_TriggerProb
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_TriggerProb(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_TriggerProb");

	Params::ConditionComponent_C_Check_TriggerProb Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Magazine_Is_Full
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Magazine_Is_Full(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Magazine_Is_Full");

	Params::ConditionComponent_C_Magazine_Is_Full Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Press_Attack
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Press_Attack(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Press_Attack");

	Params::ConditionComponent_C_Press_Attack Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.IsInteractive
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::IsInteractive(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "IsInteractive");

	Params::ConditionComponent_C_IsInteractive Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.SummonInRange
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::SummonInRange(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "SummonInRange");

	Params::ConditionComponent_C_SummonInRange Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.SummonNumMore
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::SummonNumMore(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "SummonNumMore");

	Params::ConditionComponent_C_SummonNumMore Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Skill_Grade
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Skill_Grade(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Skill_Grade");

	Params::ConditionComponent_C_Check_Skill_Grade Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_CurrentTN
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_CurrentTN(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_CurrentTN");

	Params::ConditionComponent_C_Check_CurrentTN Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Can_Gesture
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Can_Gesture(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Can_Gesture");

	Params::ConditionComponent_C_Can_Gesture Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Is_TeamHp_Below
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Is_TeamHp_Below(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Is_TeamHp_Below");

	Params::ConditionComponent_C_Is_TeamHp_Below Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Is_Hp_Above
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Is_Hp_Above(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Is_Hp_Above");

	Params::ConditionComponent_C_Is_Hp_Above Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_SecondSpRate
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_SecondSpRate(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_SecondSpRate");

	Params::ConditionComponent_C_Check_SecondSpRate Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Maer_Skill01_Grade2
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UConditionComponent_C::Check_Maer_Skill01_Grade2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Maer_Skill01_Grade2");

	Params::ConditionComponent_C_Check_Maer_Skill01_Grade2 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function ConditionComponent.ConditionComponent_C.Check_Maer_Skill01_Target
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Maer_Skill01_Target(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Maer_Skill01_Target");

	Params::ConditionComponent_C_Check_Maer_Skill01_Target Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_SecondSP
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_SecondSP(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_SecondSP");

	Params::ConditionComponent_C_Check_SecondSP Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Summoner_Check_Buff
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Summoner_Check_Buff(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Summoner_Check_Buff");

	Params::ConditionComponent_C_Summoner_Check_Buff Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_No_Bullet
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_No_Bullet(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_No_Bullet");

	Params::ConditionComponent_C_Check_No_Bullet Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Ranged_Mon_Num
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Ranged_Mon_Num(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Ranged_Mon_Num");

	Params::ConditionComponent_C_Check_Ranged_Mon_Num Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_BTTargetAngle
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_BTTargetAngle(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_BTTargetAngle");

	Params::ConditionComponent_C_Check_BTTargetAngle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_BTTargetLoc
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_BTTargetLoc(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_BTTargetLoc");

	Params::ConditionComponent_C_Check_BTTargetLoc Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Attr_Self
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Attr_Self(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Attr_Self");

	Params::ConditionComponent_C_Check_Attr_Self Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Excel_Weapon
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Excel_Weapon(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Excel_Weapon");

	Params::ConditionComponent_C_Check_Excel_Weapon Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Team_Same_Element
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Team_Same_Element(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Team_Same_Element");

	Params::ConditionComponent_C_Check_Team_Same_Element Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Attr_Element
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Attr_Element(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Attr_Element");

	Params::ConditionComponent_C_Check_Attr_Element Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_EffectTargetValid
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_EffectTargetValid(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_EffectTargetValid");

	Params::ConditionComponent_C_Check_EffectTargetValid Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Buff_Layer
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Buff_Layer(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Buff_Layer");

	Params::ConditionComponent_C_Check_Buff_Layer Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Buff_LastTime
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Buff_LastTime(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Buff_LastTime");

	Params::ConditionComponent_C_Check_Buff_LastTime Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Check_Buff
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Check_Buff(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Check_Buff");

	Params::ConditionComponent_C_Check_Buff Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Not_Shoot_Hold
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Not_Shoot_Hold(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Not_Shoot_Hold");

	Params::ConditionComponent_C_Not_Shoot_Hold Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Not_Attack_Hold
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Not_Attack_Hold(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Not_Attack_Hold");

	Params::ConditionComponent_C_Not_Attack_Hold Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Is_In_BulletJump
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Is_In_BulletJump(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Is_In_BulletJump");

	Params::ConditionComponent_C_Is_In_BulletJump Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Is_Flying
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Is_Flying(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Is_Flying");

	Params::ConditionComponent_C_Is_Flying Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Is_In_Air
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Is_In_Air(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Is_In_Air");

	Params::ConditionComponent_C_Is_In_Air Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.effect_hit_target
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::effect_hit_target(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "effect_hit_target");

	Params::ConditionComponent_C_effect_hit_target Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.hit_target
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   是否成功                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::hit_target(bool* 是否成功)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "hit_target");

	Params::ConditionComponent_C_hit_target Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (是否成功 != nullptr)
		*是否成功 = Parms.是否成功;
}


// Function ConditionComponent.ConditionComponent_C.Has_Movement_Input
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Has_Movement_Input(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Has_Movement_Input");

	Params::ConditionComponent_C_Has_Movement_Input Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Phantom_BulletJump
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Phantom_BulletJump(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Phantom_BulletJump");

	Params::ConditionComponent_C_Phantom_BulletJump Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Phantom_OwnerDis
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Phantom_OwnerDis(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Phantom_OwnerDis");

	Params::ConditionComponent_C_Phantom_OwnerDis Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Is_Phantom
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Is_Phantom(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Is_Phantom");

	Params::ConditionComponent_C_Is_Phantom Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Can_Phantom_Summon_Num
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Can_Phantom_Summon_Num(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Can_Phantom_Summon_Num");

	Params::ConditionComponent_C_Can_Phantom_Summon_Num Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Can_Phantom_Summon_Id
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Can_Phantom_Summon_Id(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Can_Phantom_Summon_Id");

	Params::ConditionComponent_C_Can_Phantom_Summon_Id Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Not_In_Battle
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Not_In_Battle(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Not_In_Battle");

	Params::ConditionComponent_C_Not_In_Battle Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.Is_In_SkillFeature
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::Is_In_SkillFeature(bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "Is_In_SkillFeature");

	Params::ConditionComponent_C_Is_In_SkillFeature Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function ConditionComponent.ConditionComponent_C.ConditionResult
// (Event, Public, BlueprintEvent)
// Parameters:
// int32                                   CombatConditionId                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bResult                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConditionComponent_C::ConditionResult(int32 CombatConditionId, bool bResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "ConditionResult");

	Params::ConditionComponent_C_ConditionResult Parms{};

	Parms.CombatConditionId = CombatConditionId;
	Parms.bResult = bResult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConditionComponent.ConditionComponent_C.ExecuteUbergraph_ConditionComponent
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UConditionComponent_C::ExecuteUbergraph_ConditionComponent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "ExecuteUbergraph_ConditionComponent");

	Params::ConditionComponent_C_ExecuteUbergraph_ConditionComponent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConditionComponent.ConditionComponent_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString UConditionComponent_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ConditionComponent_C", "GetModuleName");

	Params::ConditionComponent_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

