#pragma once

/*
* SDK generated by Dumper-DNA
*/

// Package: EF_BP_Decal

#include "Basic.hpp"

#include "EF_BP_Decal_classes.hpp"
#include "EF_BP_Decal_parameters.hpp"


namespace SDK
{

// Function EF_BP_Decal.EF_BP_Decal_C.ExecuteUbergraph_EF_BP_Decal
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AEF_BP_Decal_C::ExecuteUbergraph_EF_BP_Decal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EF_BP_Decal_C", "ExecuteUbergraph_EF_BP_Decal");

	Params::EF_BP_Decal_C_ExecuteUbergraph_EF_BP_Decal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function EF_BP_Decal.EF_BP_Decal_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AEF_BP_Decal_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EF_BP_Decal_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EF_BP_Decal.EF_BP_Decal_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void AEF_BP_Decal_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EF_BP_Decal_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function EF_BP_Decal.EF_BP_Decal_C.SetColor
// (Public, BlueprintCallable, BlueprintEvent)

void AEF_BP_Decal_C::SetColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EF_BP_Decal_C", "SetColor");

	UObject::ProcessEvent(Func, nullptr);
}

}

