#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Heitao_Skill02_Cam

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "LevelSequence_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Heitao_Skill02_Cam.SequenceDirector_C
// 0x0008 (0x0040 - 0x0038)
class Heitao_Skill02_Cam::USequenceDirector_C final : public ULevelSequenceDirector
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0038(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_SequenceDirector(int32 EntryPoint);
	void SequenceUpdateLight_1(class AEnvirSystemActor_C* Env_Ail);
	void SequenceUpdateLight_0(class AEnvirSystemActor_C* EnvirSystemActor_0);
	void SequenceEvent__ENTRYPOINTSequenceDirector_0(class AEnvirSystemActor_C* EnvirSystemActor_0);
	void SequenceEvent__ENTRYPOINTSequenceDirector_1(class AEnvirSystemActor_C* Env_Ail);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass Heitao_Skill02_Cam.SequenceDirector_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SequenceDirector_C")
	}
	static class Heitao_Skill02_Cam::USequenceDirector_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Heitao_Skill02_Cam::USequenceDirector_C>();
	}
};
DUMPER7_ASSERTS_Heitao_Skill02_Cam__USequenceDirector_C;

}

