#pragma once

/*
* SDK generated by Dumper-DNA
*/

// Package: Prologue_Clouds_Design

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Prologue_Clouds_Design.Prologue_Clouds_Design_C
// 0x0000 (0x02A8 - 0x02A8)
class APrologue_Clouds_Design_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Prologue_Clouds_Design_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Prologue_Clouds_Design_C")
	}
	static class APrologue_Clouds_Design_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APrologue_Clouds_Design_C>();
	}
};
DUMPER7_ASSERTS_APrologue_Clouds_Design_C;

}

