#pragma once

/*
* SDK generated by Dumper-DNA
*/

// Package: ResourceNew

#include "Basic.hpp"

#include "ResourceNew_classes.hpp"
#include "ResourceNew_parameters.hpp"


namespace SDK
{

// Function ResourceNew.ResourceNew_C.ExecuteUbergraph_ResourceNew
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AResourceNew_C::ExecuteUbergraph_ResourceNew(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ResourceNew_C", "ExecuteUbergraph_ResourceNew");

	Params::ResourceNew_C_ExecuteUbergraph_ResourceNew Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ResourceNew.ResourceNew_C.ReceiveBeginPlay
// (Native, Event, Protected, BlueprintEvent)

void AResourceNew_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ResourceNew_C", "ReceiveBeginPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}

}

