#pragma once

/*
* SDK generated by Dumper-DNA
*/

// Package: SQ_Login_FTM

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "LevelSequence_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SQ_Login_FTM.SequenceDirector_C
// 0x0008 (0x0040 - 0x0038)
class SQ_Login_FTM::USequenceDirector_C final : public ULevelSequenceDirector
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0038(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_SequenceDirector(int32 EntryPoint);
	void OnFinished_Event_0();
	void OnCreated();
	void Loop(int32 StartFrame);
	void SequenceEvent__ENTRYPOINTSequenceDirector_0();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL_FULLNAME("BlueprintGeneratedClass SQ_Login_FTM.SequenceDirector_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SequenceDirector_C")
	}
	static class SQ_Login_FTM::USequenceDirector_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<SQ_Login_FTM::USequenceDirector_C>();
	}
};
DUMPER7_ASSERTS_SQ_Login_FTM__USequenceDirector_C;

}

