#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: St_PetSkin

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK
{

// UserDefinedStruct St_PetSkin.St_PetSkin
// 0x0020 (0x0020 - 0x0000)
struct FSt_PetSkin final
{
public:
	struct FLinearColor                           EmissiveColor_6_5F2AA863419E6404CA7FCCB9815AD4EE;  // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           FresnelColor_7_B5CC96B24E822A042B44F88D3094B45E;   // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FSt_PetSkin;

}

