#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Story_Image

#include "Basic.hpp"

#include "EM_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Story_Image.WBP_Story_Image_C
// 0x0000 (0x02A0 - 0x02A0)
class UWBP_Story_Image_C final : public UImageSequencerWidget
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Story_Image_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Story_Image_C")
	}
	static class UWBP_Story_Image_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Story_Image_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Story_Image_C;

}

