#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Instruction_Text

#include "Basic.hpp"

#include "WBP_Instruction_Text_classes.hpp"
#include "WBP_Instruction_Text_parameters.hpp"


namespace SDK
{

// Function WBP_Instruction_Text.WBP_Instruction_Text_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString UWBP_Instruction_Text_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Instruction_Text_C", "GetModuleName");

	Params::WBP_Instruction_Text_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

