#pragma once

/*
* SDK generated by Dumper-DNA
*/

// Package: WBP_GuidePoint_Phantom

#include "Basic.hpp"

#include "WBP_GuidePoint_Phantom_classes.hpp"
#include "WBP_GuidePoint_Phantom_parameters.hpp"


namespace SDK
{

// Function WBP_GuidePoint_Phantom.WBP_GuidePoint_Phantom_C.ExecuteUbergraph_WBP_GuidePoint_Phantom
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_GuidePoint_Phantom_C::ExecuteUbergraph_WBP_GuidePoint_Phantom(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuidePoint_Phantom_C", "ExecuteUbergraph_WBP_GuidePoint_Phantom");

	Params::WBP_GuidePoint_Phantom_C_ExecuteUbergraph_WBP_GuidePoint_Phantom Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_GuidePoint_Phantom.WBP_GuidePoint_Phantom_C.VX_Common_GuidePoint_Phantom_Resurgence_Press
// (BlueprintCallable, BlueprintEvent)

void UWBP_GuidePoint_Phantom_C::VX_Common_GuidePoint_Phantom_Resurgence_Press()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuidePoint_Phantom_C", "VX_Common_GuidePoint_Phantom_Resurgence_Press");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GuidePoint_Phantom.WBP_GuidePoint_Phantom_C.VX_Common_GuidePoint_Phantom_Dead_Teammate
// (BlueprintCallable, BlueprintEvent)

void UWBP_GuidePoint_Phantom_C::VX_Common_GuidePoint_Phantom_Dead_Teammate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuidePoint_Phantom_C", "VX_Common_GuidePoint_Phantom_Dead_Teammate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GuidePoint_Phantom.WBP_GuidePoint_Phantom_C.VX_Common_GuidePoint_Phantom_Suspend
// (BlueprintCallable, BlueprintEvent)

void UWBP_GuidePoint_Phantom_C::VX_Common_GuidePoint_Phantom_Suspend()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuidePoint_Phantom_C", "VX_Common_GuidePoint_Phantom_Suspend");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GuidePoint_Phantom.WBP_GuidePoint_Phantom_C.VX_Common_GuidePoint_Phantom_Resurgence_Success
// (BlueprintCallable, BlueprintEvent)

void UWBP_GuidePoint_Phantom_C::VX_Common_GuidePoint_Phantom_Resurgence_Success()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuidePoint_Phantom_C", "VX_Common_GuidePoint_Phantom_Resurgence_Success");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GuidePoint_Phantom.WBP_GuidePoint_Phantom_C.VX_Common_GuidePoint_Phantom_Resurgence
// (BlueprintCallable, BlueprintEvent)

void UWBP_GuidePoint_Phantom_C::VX_Common_GuidePoint_Phantom_Resurgence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuidePoint_Phantom_C", "VX_Common_GuidePoint_Phantom_Resurgence");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GuidePoint_Phantom.WBP_GuidePoint_Phantom_C.VX_Common_GuidePoint_Phantom_Dead
// (BlueprintCallable, BlueprintEvent)

void UWBP_GuidePoint_Phantom_C::VX_Common_GuidePoint_Phantom_Dead()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuidePoint_Phantom_C", "VX_Common_GuidePoint_Phantom_Dead");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GuidePoint_Phantom.WBP_GuidePoint_Phantom_C.VX_Common_GuidePoint_Phantom_Normal
// (BlueprintCallable, BlueprintEvent)

void UWBP_GuidePoint_Phantom_C::VX_Common_GuidePoint_Phantom_Normal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuidePoint_Phantom_C", "VX_Common_GuidePoint_Phantom_Normal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_GuidePoint_Phantom.WBP_GuidePoint_Phantom_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString UWBP_GuidePoint_Phantom_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_GuidePoint_Phantom_C", "GetModuleName");

	Params::WBP_GuidePoint_Phantom_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

