#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_NPC_HeadIcon_Impresssion

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "EM_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_NPC_HeadIcon_Impresssion.WBP_NPC_HeadIcon_Impresssion_C
// 0x0020 (0x05F0 - 0x05D0)
class UWBP_NPC_HeadIcon_Impresssion_C final : public UEMUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05D0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Out;                                               // 0x05D8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       In;                                                // 0x05E0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Image_Icon;                                        // 0x05E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void ExecuteUbergraph_WBP_NPC_HeadIcon_Impresssion(int32 EntryPoint);

	class FString GetModuleName() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_NPC_HeadIcon_Impresssion_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_NPC_HeadIcon_Impresssion_C")
	}
	static class UWBP_NPC_HeadIcon_Impresssion_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_NPC_HeadIcon_Impresssion_C>();
	}
};
DUMPER7_ASSERTS_UWBP_NPC_HeadIcon_Impresssion_C;

}

