#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WordFadeTimeMod

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum WordFadeTimeMod.WordFadeTimeMod
// NumValues: 0x0005
enum class EWordFadeTimeMod : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator2                           = 1,
	NewEnumerator1                           = 2,
	NewEnumerator3                           = 3,
	WordFadeTimeMod_MAX                      = 4,
};

}

